spring:
  # 将所有数字转为 String 类型返回，避免前端数据精度丢失的问题
  jackson:
    generator:
      write-numbers-as-strings: true
  cache:
    type: redis
    redis:
      # 是否打开键前缀
      use-key-prefix: false
      # 是否缓存空值
      cache-null-values: false
      # 设置键前缀
      #      key-prefix: sms_
      # 设置生命周期
      time-to-live: 10s
  redis:
    host: 192.168.139.101
    port: 6379
    password: drg1224605
    database: 0
    connect-timeout: 5000
  #  datasource:
  #    username: root
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    password: drg1224605
  #    url: jdbc:mysql://localhost:3306/reggie?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  shardingsphere:
    datasource:
      names: master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: drg1224605
        url: jdbc:mysql://192.168.139.102:3306/reggie?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: drg1224605
        url: jdbc:mysql://192.168.139.103:3306/reggie?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
      masterslave:
        # 读写分离配置
        load-balance-algorithm-type: round_robin # 轮询
        # 最终的数据源名称
        name: dataSource
        # 主库数据源名称
        master-data-source-name: master
        # 从库数据源名称列表,多个逗号分隔
        slave-data-source-names: slave
      props:
        sql:
          # 开启sql显示，默认为false
          show: true
  main:
    # 允许bean定义覆盖
    allow-bean-definition-overriding: true