server:
  port: 8081
spring:
  application:
    name: raj
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher